// measurement
export const GET_MEASUREMENT_REQUEST = 'GET_MEASUREMENT_REQUEST'
export const GET_MEASUREMENT_SUCCESS = 'GET_MEASUREMENT_SUCCESS'
export const GET_MEASUREMENT_FAILURE = 'GET_MEASUREMENT_FAILURE'

export const ADD_MEASUREMENT_REQUEST = 'ADD_MEASUREMENT_REQUEST'
export const ADD_MEASUREMENT_SUCCESS = 'ADD_MEASUREMENT_SUCCESS'
export const ADD_MEASUREMENT_FAILURE = 'ADD_MEASUREMENT_FAILURE'