// Measurement Actions (Server)
export const GET_MEASUREMENT_REQUEST = 'GET_MEASUREMENT_REQUEST'
export const GET_MEASUREMENT_SUCCESS = 'GET_MEASUREMENT_SUCCESS'
export const GET_MEASUREMENT_FAILURE = 'GET_MEASUREMENT_FAILURE'

export const ADD_MEASUREMENT_REQUEST = 'ADD_MEASUREMENT_REQUEST'
export const ADD_MEASUREMENT_SUCCESS = 'ADD_MEASUREMENT_SUCCESS'
export const ADD_MEASUREMENT_FAILURE = 'ADD_MEASUREMENT_FAILURE'

export const SELECT_DATE = 'SELECT_DATE'

// Device Actions (Measure Screen)
export const MEASURE_TEMPERATURE_LOADING = 'MEASURE_TEMPERATURE_LOADING'
export const MEASURE_TEMPERATURE_VALUE = 'MEASURE_TEMPERATURE_VALUE'
export const MEASURE_TEMPERATURE_FAILURE = 'MEASURE_TEMPERATURE_FAILURE'

export const MEASURE_BLOOD_PRESSURE_LOADING = 'MEASURE_BLOOD_PRESSURE_LOADING'
export const MEASURE_BLOOD_PRESSURE_VALUE = 'MEASURE_BLOOD_PRESSURE_VALUE'
export const MEASURE_BLOOD_PRESSURE_FAILURE = 'MEASURE_BLOOD_PRESSURE_FAILURE'

export const MEASURE_OXIMETER_LOADING = 'MEASURE_OXIMETER_LOADING'
export const MEASURE_OXIMETER_VALUE = 'MEASURE_OXIMETER_VALUE'
export const MEASURE_OXIMETER_FAILURE = 'MEASURE_OXIMETER_FAILURE'